version: '3.8'

services:
  weather-api-db:
    container_name: weather-api-db
    image: postgres
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_db_user
      POSTGRES_PASSWORD: weather_db_password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-order:/data/postgres
    expose:
      - "5432"
    restart: unless-stopped

  weather-api-redis:
    container_name: weather-api-redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  weather-api-service:
    container_name: weather-api-service
    image: weather-api-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://weather-api-db:5432/weather_db
      - SPRING_REDIS_HOST=weather-api-redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - weather-api-db
      - weather-api-redis
    ports:
      - "8080:8080"
